# If a URL to a repo containing secrets used in dotfiles was provided, add it as a git submodule.
{{ if ne .secretsRepo "" }}
["secrets"]
type = "git-repo"
url = {{ .secretsRepo | quote }}
branch = "main"
refreshPeriod = "8h"
{{ end }}
