unused = "#79e11a"

[tokyonight]
gray1 = "#414868"
gray2 = "#565f89"
gray3 = "#787c99"
gray4 = "#a9b1d6"
black = "#1a1b26"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
purple = "#9d7cd8"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[dark]
button = ["tokyonight.black", "tokyonight.gray3"]
button-focus = ["tokyonight.black", "tokyonight.magenta"]
button-selected = ["tokyonight.white", "tokyonight.gray3"]
cmdline = ["tokyonight.black", "tokyonight.yellow"]
cmdline-button = ["tokyonight.yellow", "tokyonight.black"]
cmdline-border = ["tokyonight.black", "tokyonight.yellow"]
copy-mode = ["tokyonight.black", "tokyonight.yellow"]
copy-mode-alt = ["tokyonight.yellow", "tokyonight.black"]
copy-mode-label = ["tokyonight.white", "tokyonight.red"]
current-capture = ["tokyonight.white", "themes.unused"]
dialog = ["tokyonight.black", "tokyonight.yellow"]
dialog-button = ["tokyonight.yellow", "tokyonight.black"]
default = ["tokyonight.white", "tokyonight.black"]
filter-empty = ["tokyonight.black", "tokyonight.cyan"]
filter-intermediate = ["tokyonight.black", "tokyonight.orange"]
filter-invalid = ["tokyonight.black", "tokyonight.red"]
filter-menu = ["tokyonight.white", "tokyonight.black"]
filter-valid = ["tokyonight.black", "tokyonight.green"]
hex-byte-selected = ["tokyonight.white", "tokyonight.purple"]
hex-byte-unselected = ["tokyonight.white", "tokyonight.black"]
hex-field-selected = ["tokyonight.black", "tokyonight.cyan"]
hex-field-unselected = ["tokyonight.black", "tokyonight.white"]
hex-interval-selected = ["tokyonight.white", "tokyonight.gray2"]
hex-interval-unselected = ["tokyonight.white", "tokyonight.gray1"]
hex-layer-selected = ["tokyonight.white", "tokyonight.gray2"]
hex-layer-unselected = ["tokyonight.white", "tokyonight.gray1"]
packet-list-cell-focus = ["tokyonight.white", "tokyonight.purple"]
packet-list-cell-selected = ["tokyonight.white", "tokyonight.gray2"]
packet-list-row-focus = ["tokyonight.white", "tokyonight.cyan"]
packet-list-row-selected = ["tokyonight.white", "tokyonight.gray1"]
packet-struct-focus = ["tokyonight.black", "tokyonight.cyan"]
packet-struct-selected = ["tokyonight.black", "tokyonight.gray2"]
progress-complete = ["tokyonight.white", "tokyonight.purple"]
progress-default = ["tokyonight.white", "tokyonight.black"]
progress-spinner = ["tokyonight.yellow", "tokyonight.purple"]
spinner = ["tokyonight.yellow", "tokyonight.black"]
stream-client = ["tokyonight.black", "tokyonight.red"]
stream-match = ["tokyonight.black", "tokyonight.yellow"]
stream-search = ["tokyonight.black", "tokyonight.white"]
stream-server = ["tokyonight.white", "tokyonight.blue"]
title = ["tokyonight.red", "unused"]

[light]
button = ["tokyonight.black", "tokyonight.white"]
button-focus = ["tokyonight.black", "tokyonight.purple"]
button-selected = ["tokyonight.black", "tokyonight.gray3"]
cmdline = ["tokyonight.black", "tokyonight.yellow"]
cmdline-button = ["tokyonight.yellow", "tokyonight.black"]
cmdline-border = ["tokyonight.black", "tokyonight.yellow"]
copy-mode = ["tokyonight.white", "tokyonight.yellow"]
copy-mode-alt = ["tokyonight.yellow", "tokyonight.white"]
copy-mode-label = ["tokyonight.black", "tokyonight.red"]
current-capture = ["tokyonight.black", "unused"]
dialog = ["tokyonight.black", "tokyonight.yellow"]
dialog-button = ["tokyonight.yellow", "tokyonight.black"]
default = ["tokyonight.black", "tokyonight.white"]
filter-empty = ["tokyonight.black", "tokyonight.cyan"]
filter-intermediate = ["tokyonight.black", "tokyonight.orange"]
filter-invalid = ["tokyonight.black", "tokyonight.red"]
filter-menu = ["tokyonight.black", "tokyonight.white"]
filter-valid = ["tokyonight.black", "tokyonight.green"]
hex-byte-selected = ["tokyonight.white", "tokyonight.purple"]
hex-byte-unselected = ["tokyonight.black", "tokyonight.white"]
hex-field-selected = ["tokyonight.black", "tokyonight.cyan"]
hex-field-unselected = ["tokyonight.black", "tokyonight.gray2"]
hex-interval-selected = ["tokyonight.white", "tokyonight.gray2"]
hex-interval-unselected = ["tokyonight.black", "tokyonight.gray4"]
hex-layer-selected = ["tokyonight.white", "tokyonight.gray2"]
hex-layer-unselected = ["tokyonight.black", "tokyonight.gray4"]
packet-list-cell-focus = ["tokyonight.white", "tokyonight.purple"]
packet-list-cell-selected = ["tokyonight.black", "tokyonight.gray3"]
packet-list-row-focus = ["tokyonight.white", "tokyonight.cyan"]
packet-list-row-selected = ["tokyonight.black", "tokyonight.gray4"]
packet-struct-focus = ["tokyonight.black", "tokyonight.cyan"]
packet-struct-selected = ["tokyonight.black", "tokyonight.gray4"]
progress-complete = ["tokyonight.white", "tokyonight.purple"]
progress-default = ["tokyonight.white", "tokyonight.black"]
progress-spinner = ["tokyonight.yellow", "tokyonight.black"]
spinner = ["tokyonight.yellow", "tokyonight.white"]
stream-client = ["tokyonight.white", "tokyonight.red"]
stream-match = ["tokyonight.white", "tokyonight.yellow"]
stream-search = ["tokyonight.white", "tokyonight.black"]
stream-server = ["tokyonight.white", "tokyonight.blue"]
title = ["tokyonight.red", "unused"]

