#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_COLOR_THEME="${NB_COLOR_THEME:-forest}" # Set by `nb` • Sat Dec 14 15:20:27 CST 2024
export EDITOR="nvim"                              # Set by `nb` • Sat Dec 14 17:24:52 CST 2024
export NB_DIRECTORY_TOOL="yazi"
export NB_FOOTER="${NB_FOOTER:-1}" # Set by `nb` • Sun Dec 22 02:49:40 CST 2024
export NB_FOLDERS_FIRST=1
export NB_MARKDOWN_TOOL="bat"

# 
export NB_INDICATOR_AUDIO=
export NB_INDICATOR_BOOKMARK=
# 
export NB_INDICATOR_DOCUMENT=
export NB_INDICATOR_EBOOK=
export NB_INDICATOR_ENCRYPTED=
export NB_INDICATOR_FOLDER=
export NB_INDICATOR_IMAGE=
export NB_INDICATOR_PINNED=
#      
export NB_INDICATOR_TODO=
export NB_INDICATOR_TODO_DONE=
export NB_INDICATOR_VIDEO=
