return {
  -- "carlos-algms/agentic.nvim",
  -- -- "krbylit/agentic.nvim",
  -- -- commit = "c1e0db8251dc2b57f5fb4f6d1097476be5bbe413",
  -- event = "VeryLazy",
  -- dependencies = {
  --   {
  --     "hakonharnes/img-clip.nvim",
  --   },
  -- },
  -- opts = {
  --   -- Available by default: "claude-acp" | "gemini-acp" | "codex-acp" | "opencode-acp"
  --   provider = "claude-acp", -- setting the name here is all you need to get started
  --   keymaps = {
  --     -- --- Keys bindings for ALL buffers in the widget
  --     -- widget = {
  --     --     close = "q",
  --     --     change_mode = {
  --     --         {
  --     --             "<S-Tab>",
  --     --             mode = { "i", "n", "v" },
  --     --         },
  --     --     },
  --     -- },
  --
  --     --- Keys bindings for the prompt buffer
  --     prompt = {
  --       -- submit = {
  --       --     "<CR>",
  --       --     {
  --       --         "<C-s>",
  --       --         mode = { "i", "n", "v" },
  --       --     },
  --       -- },
  --
  --       paste_image = {
  --         {
  --           -- We must override default <localleader>p because this causes issues when typing space + p quickly
  --           "<C-p>", -- Default keybinding for pasting images
  --           mode = { "n", "i" },
  --         },
  --       },
  --     },
  --   },
  -- },
  -- -- these are just suggested keymaps; customize as desired
  -- keys = {
  --   {
  --     "<C-\\>",
  --     function()
  --       require("agentic").toggle()
  --     end,
  --     mode = { "n", "v", "i" },
  --     desc = "Toggle Agentic Chat",
  --   },
  --   {
  --     "<C-'>",
  --     function()
  --       require("agentic").add_selection_or_file_to_context()
  --     end,
  --     mode = { "n", "v" },
  --     desc = "Add file or selection to Agentic to Context",
  --   },
  --   {
  --     "<C-,>",
  --     function()
  --       require("agentic").new_session()
  --     end,
  --     mode = { "n", "v", "i" },
  --     desc = "New Agentic Session",
  --   },
  --   -- {
  --   --   "<leader>at",
  --   --   function()
  --   --     require("agentic").toggle()
  --   --   end,
  --   --   mode = { "n", "v", "i" },
  --   --   desc = "Toggle Agentic Chat",
  --   -- },
  --   {
  --     "<leader>ac",
  --     function()
  --       require("agentic").add_selection_or_file_to_context()
  --     end,
  --     mode = { "n", "v" },
  --     desc = "Add file or selection to Agentic to Context",
  --   },
  --   {
  --     "<leader>an",
  --     function()
  --       require("agentic").new_session()
  --     end,
  --     mode = { "n", "v", "i" },
  --     desc = "New Agentic Session",
  --   },
  -- },
}
