# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{
[flavor]
# dark = "tokyo-night"
# # NOTE: tokyonight tabs are very difficult to read unless colored manually
# [tabs]
# active = { fg = "#2E3440", bg = "#8FBCBB", bold = true } # nord0 on nord7 (Teal/Mint)
# inactive = { fg = "#8FBCBB", bg = "#3B4252" }            # nord7 on nord1

# dark = "onedark"
dark = "nord"
# dark = "kanagawa"
# dark = "vscode-dark-plus"
# dark = "rose-pine"
# dark = "catppuccin-macchiato"
# light = "catppuccin-latte"

[mgr]
# FIXME: doesn't seem to be making any effect
# syntect_theme = "./flavors/catppuccin-macchiato.yazi/tmtheme.xml"
# syntect_theme = "flavors/vscode-dark-modern.yazi/tmtheme.xml"


# : }}}
