[uv]
tools = [
    { name = "pip", ssh = true },
    { name = "pipx", ssh = true },
    { name = "ruff-lsp", ssh = true },
    { name = "ruff", ssh = true },
    { name = "pre-commit", ssh = true },
    { name = "yapf", ssh = true },
    { name = "bagels" },
    { name = "cfn-lint" },
    { name = "neovim-remote", ssh = true },
    { name = "terminaltexteffects" },
]
