name: Daily Sync from Private Dev

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  sync_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Dev Branch
        uses: actions/checkout@v4
        with:
          ref: dev # Fetch only the dev branch

      - name: Set Up Git User (GitHub Actions Bot)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Add Private Repo with SSH Authentication
      - name: Add Private Repo as Remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOTFILES_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote add private git@github.com:krbylit/dotfiles-private.git
          git fetch private dev

      # Force Sync Private Dev into Public Dev with Custom Commit Message
      - name: Force Sync Private Dev into Public Dev
        run: |
          git fetch private dev
          git checkout dev
          git pull origin dev || true

          # Hard overwrite public dev with private dev (no history retained)
          git reset --mixed private/dev
          git add .

          # Create a squash commit with hash, message, and author
          git commit -m "$(git log private/dev --pretty=format:'%h - %s%n%bAuthor: %an <%ae>' -1)"
          git push origin dev --force
