name: Daily Sync from Private Dev (Cherry-Pick with Per-Commit Conflict Resolution)

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  sync_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Dev Branch
        uses: actions/checkout@v4
        with:
          ref: dev # Fetch only the dev branch

      - name: Set Up Git User (GitHub Actions Bot)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Add Private Repo with SSH Authentication
      - name: Add Private Repo as Remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOTFILES_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote add private git@github.com:krbylit/dotfiles-private.git
          git fetch private dev

      # Cherry-Pick New Commits from Private Dev with Per-Commit Conflict Handling
      - name: Cherry-Pick and Resolve Conflicts Per Commit
        run: |
          git fetch private dev
          git checkout dev
          git pull origin dev || true

          # Identify new commits to cherry-pick
          COMMITS=$(git log origin/dev..private/dev --reverse --pretty=format:"%H")

          # Cherry-pick each commit individually
          if [ -n "$COMMITS" ]; then
            for commit in $COMMITS; do
              echo "Cherry-picking commit $commit"
              git cherry-pick $commit || (
                echo "Conflict detected for commit $commit - Resolving with private state."
                
                # Only resolve conflicts for the current commit (keep private changes)
                git diff --name-only --diff-filter=U | xargs git checkout private/dev --
                
                # Stage and commit the resolved changes
                git add .
                git commit --no-edit
              )
            done
            git push origin dev --force
          else
            echo "No new commits to cherry-pick. Exiting gracefully."
          fi
