name: Daily Squash Merge from Private Dev

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1 AM UTC
  workflow_dispatch: # Allow manual triggering if needed

jobs:
  squash_merge_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo (dotfiles)
        uses: actions/checkout@v4

      - name: Set Up Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Pull Changes from Private Dev Branch
        run: |
          git remote add private https://krbylit:${{ secrets.GH_PAT }}@github.com/krbylit/dotfiles-private.git
          git fetch private dev

      - name: Squash Merge with Commit Messages
        run: |
          git checkout main
          git merge --squash private/dev

          # Prepare a detailed commit message with authors
          git log private/dev --pretty=format:"%h - %s%n%b%nAuthor: %an <%ae>%n" > commit_message.txt
          git commit -F commit_message.txt
          git push origin main
